version: '3.2'

services: 
  db:
    image: db/mysql:1.0
    build: ./db
    container_name: 'db'
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes: 
      - ./db/mysql:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  server:
    image: server/embulk:1.0
    build: ./server
    container_name: 'emb'
    ports:
      - "5432:5432"
    env_file:
      - .env
    tty: true
    stdin_open: true
    volumes:
      - ./server/app:/app
    depends_on:
      - db
